# Generated by Django 3.2.13 on 2022-06-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choix1', models.CharField(max_length=80)),
                ('choix2', models.CharField(max_length=80)),
                ('choix3', models.CharField(max_length=80)),
                ('choix4', models.CharField(max_length=80)),
                ('reponse', models.CharField(max_length=80)),
            ],
        ),
        migrations.RenameField(
            model_name='video',
            old_name='discription',
            new_name='description',
        ),
        migrations.CreateModel(
            name='Quizze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('questions', models.ManyToManyField(to='app1.Question')),
            ],
        ),
    ]
